---
- name: Install epel repository
  yum:
    name: epel-release
    state: present
    validate_certs: yes
  become: yes

- name: Disable epel repository
  replace:
    path: /etc/yum.repos.d/epel.repo
    regexp: "enabled *= *1"
    replace: "enabled=0"
  when: epel.disabled
  become: yes
